import type { Metadata } from "next";
import { ChakraProvider } from "@chakra-ui/react";
import { Bebas_Neue } from "next/font/google";
import "./globals.css";

const inter = Bebas_Neue({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
    title: "Burner",
    description: "Generated by create next app",
    icons: {
        icon: "/favicon.ico",
    },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <ChakraProvider>
                    {children}
                </ChakraProvider>
            </body>
        </html>
    );
}
